import type { AffiliateArticle } from './affiliateData';

const SYSTEME_IO_AFFILIATE_URL = 'https://systeme.io/jp?sa=sa0280926250afeb54ccbe34abfc78fa154603223e';

export const extraArticles: AffiliateArticle[] = [
  {
    slug: 'systeme-io-alternatives',
    title: 'systeme.ioの代替候補は？Kajabi・ClickFunnels・Thinkificと比べて選ぶ',
    description: 'systeme.ioの代替候補を用途別に比較。価格、講座販売、ファネル、メール、運用の違いから、どのサービスが向くかを整理します。',
    service: 'systeme.io 比較',
    intent: '代替・購入直前',
    updated: '2026-09-07',
    affiliateUrl: SYSTEME_IO_AFFILIATE_URL,
    affiliatePending: false,
    intro: 'systeme.ioが合わない可能性まで含めて比較したい人向けです。結論から言うと、低コストで販売導線をまとめたいならsysteme.io、講座体験を深く作るならThinkific、ブランド型の知識ビジネスを大きく育てるならKajabi、ファネル運用を強く重視するならClickFunnelsが候補です。',
    sections: [
      { heading: '価格を抑えて一通り試したいならsysteme.io', body: ['systeme.ioは無料プランがあり、公式の料金ページでは無料から始められます。LP、メール、コース、ファネルなどをまとめて試したい人に向きます。', '固定費をまだ増やしたくない副業・個人事業では、まず無料で検証できること自体が大きな強みです。'] },
      { heading: '講座そのものを中心にするならThinkific', body: ['Thinkificは講座作成・受講者体験を中心に考えたい人向けです。2026年8月以降の公式価格ではBasicが月額54ドル、Startが109ドル、Growが219ドルと案内されています。', 'メールや販売ファネルを別で強く使うなら、周辺ツールとの組み合わせも含めて判断する必要があります。'] },
      { heading: 'Kajabiは高価格帯だがブランド事業向け', body: ['Kajabiの公式価格はBasicが月額179ドル、Growthが249ドル、Proが499ドル。年払いでは割引があります。', '商品数・コミュニティ・マーケティングまでまとめて本格運用したい人には候補ですが、まだ売上がない段階では固定費が重くなりやすいです。'] },
      { heading: 'ClickFunnelsはファネル最優先の人向け', body: ['ClickFunnelsの2026年公式価格はLaunch 97ドル、Scale 197ドル、Optimize 297ドル。セールスファネル中心で設計したい人には強い候補です。', '一方で、最初の1商品を小さく売る段階では、必要以上に高機能・高コストになる可能性があります。'] },
      { heading: '迷ったら「今の売上規模」で決める', body: ['まだ売上検証前ならsysteme.ioの無料プランから始め、講座事業が伸びて受講体験を深めたいならThinkific、知識ビジネス全体をブランド化したいならKajabi、ファネルを本格運用したいならClickFunnelsという順で考えると判断しやすいです。'] },
    ],
    cta: 'systeme.ioを無料で試して比較する',
  },
  {
    slug: 'systeme-io-vs-kajabi',
    title: 'systeme.ioとKajabiを比較｜月額差に見合う違いはある？',
    description: 'systeme.ioとKajabiを価格・講座・メール・ファネル・事業規模で比較。副業から本格知識ビジネスまで、どちらが向くか整理します。',
    service: 'systeme.io × Kajabi',
    intent: '比較・購入直前',
    updated: '2026-09-07',
    affiliateUrl: SYSTEME_IO_AFFILIATE_URL,
    affiliatePending: false,
    intro: 'この2つは「オールインワン」という点は似ていますが、狙っている事業規模がかなり違います。最初の売上を作る段階ならsysteme.io、本格的なブランド型知識ビジネスならKajabiが候補です。',
    sections: [
      { heading: '価格差はかなり大きい', body: ['systeme.ioは無料プランから始められます。Kajabiは公式価格でBasicが月額179ドル、Growthが249ドル、Proが499ドルです。', 'まだ販売検証前なら、Kajabiの固定費を先に背負うより、systeme.ioで売れる導線を先に確認する方が合理的なケースが多いです。'] },
      { heading: 'Kajabiはブランド事業の完成度を上げたい人向け', body: ['Kajabiは商品、コミュニティ、Webサイト、マーケティングなどをまとめて運用したい知識ビジネス向けです。すでに顧客がいて、見せ方や運用の完成度に投資できる段階なら価値が出やすいです。'] },
      { heading: 'systeme.ioは最短で売れる形を作りたい人向け', body: ['systeme.ioは、機能の豪華さより「販売に必要なものをまとめて、低コストで始める」ことに強みがあります。', '副業・個人サービス・初回講座など、まず成約が発生する導線を作りたい人には相性があります。'] },
      { heading: '結論', body: ['売上検証前〜小規模ならsysteme.io、本格的に知識ビジネスへ投資する段階ならKajabi。どちらが上というより、今の事業フェーズで選ぶのが正解です。'] },
    ],
    cta: 'systeme.ioを無料で試して判断する',
  },
  {
    slug: 'systeme-io-vs-clickfunnels',
    title: 'systeme.ioとClickFunnelsを比較｜ファネル販売ならどっち？',
    description: 'systeme.ioとClickFunnelsを価格・ファネル・メール・講座・事業規模で比較。売る仕組みを作るならどちらが向くか整理します。',
    service: 'systeme.io × ClickFunnels',
    intent: '比較・購入直前',
    updated: '2026-09-07',
    affiliateUrl: SYSTEME_IO_AFFILIATE_URL,
    affiliatePending: false,
    intro: 'どちらも販売ファネルを作れますが、最初に見るべき違いは価格と「どこまで本格運用するか」です。小さく始めるならsysteme.io、ファネルを事業の中心に据えるならClickFunnelsが候補です。',
    sections: [
      { heading: 'ClickFunnelsはファネル特化の本格派', body: ['ClickFunnelsの公式価格は2026年時点でLaunch 97ドル、Scale 197ドル、Optimize 297ドル。無制限ファネルやワークスペース、AIツールなど、ファネル事業を伸ばすための機能が揃っています。'] },
      { heading: 'systeme.ioは無料から検証できる', body: ['systeme.ioは無料プランがあり、商品がまだ売れるか分からない段階でも固定費をかけずに販売導線を試せます。', '副業で最初の1商品を売る段階なら、この差はかなり大きいです。'] },
      { heading: '高機能が必要になる時点まで待っても遅くない', body: ['最初から複雑なファネルを組む必要がないなら、まずsysteme.ioで集客・登録・販売を一巡させる方が速いです。', '売上が伸び、複数ブランドや高度なファネル運用が必要になった段階でClickFunnelsを再検討できます。'] },
      { heading: '結論', body: ['「売れるか検証したい」ならsysteme.io、「ファネル運用そのものを競争力にしたい」ならClickFunnels。この線引きで選ぶと分かりやすいです。'] },
    ],
    cta: 'systeme.ioを無料で試して比較する',
  },
  {
    slug: 'online-course-platform-free',
    title: 'オンライン講座販売を無料で始めるなら？最初に固定費をかけない選び方',
    description: 'オンライン講座販売を無料・低コストで始めたい人向け。講座作成、LP、メール、販売導線まで含めて、最初の選び方を整理します。',
    service: 'オンライン講座',
    intent: '無料・購入直前',
    updated: '2026-09-07',
    affiliateUrl: SYSTEME_IO_AFFILIATE_URL,
    affiliatePending: false,
    intro: '講座販売は、受講ページだけ作っても売れません。必要なのは「集客 → 登録 → 案内 → 決済 → 受講」の流れです。最初はこの一連をできるだけ固定費ゼロで試す方が失敗しにくいです。',
    sections: [
      { heading: '無料で始めるなら「講座だけ」ではなく販売導線を見る', body: ['オンライン講座ツールを選ぶとき、動画を置けるかだけで判断すると、後からLP・メール配信・ファネルの費用が増えます。', '最初の売上が出るまでは、販売導線全体を一つの環境で試せるかを見る方が重要です。'] },
      { heading: 'systeme.ioは無料プランで講座販売を試せる', body: ['systeme.ioの日本語公式ページでは、無料プランで1コースと2,000件の受講者コンタクトを利用できると案内されています。取引手数料もsysteme.io側は0%です。', '講座、LP、メール、販売導線を同じ環境で試せるため、最初の検証コストを下げやすいです。'] },
      { heading: '有料ツールは売れてからでも遅くない', body: ['ThinkificやKajabiのような有力サービスもありますが、最初から月額費用を背負う必要があるかは別問題です。', 'まず1講座を出し、申込が発生し、運用上の不満が具体化してから上位サービスへ移る方が判断しやすくなります。'] },
      { heading: '最初の目標は「完璧な講座」ではなく「最初の1件」', body: ['デザインや機能を作り込むより、1つの商品ページ、数通のメール、最低限の講座内容で実際に販売を始める方が学びが早いです。'] },
    ],
    cta: '無料で講座販売の導線を作ってみる',
  },
];
